# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  - stage: sandbox
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    dependsOn: []
    jobs:
    - template: yaml-templates/build.yml  # Template reference
      parameters:
        solution: $(solution)
        buildPlatform: $(buildPlatform)
        buildConfiguration: $(buildConfiguration)
    - template: yaml-templates/release.yml  # Template reference
      dependsOn: yaml-templates/build.yml